#VIA_ENABLE = yes
#CONSOLE_ENABLE = yes
# LTO_ENABLE = yes
# MOUSEKEY_ENABLE = yes       # Mouse keys
COMBO_ENABLE = no
BOOTLOADER=qmk-dfu
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
